stages:
  Load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/get_data.py
    - src/load_data.py
    - data_given/WineQua.csv
    outs:
    - data/raw/WineQua.csv

  Split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - data/raw/WineQua.csv
    - src/split_data.py    
    outs:
    - data/processed/train_winequality.csv
    - data/processed/test_winequality.csv  